name: DisabledSMP
version: '1.0-SNAPSHOT'
main: de.joja.disabledSMP.DisabledSMP
api-version: '1.21'

commands:
  dis:
    description: Manage disabilities
    usage: /dis <add|rm|menu> [args]

permissions:
  disabledSMP.disability_admin:
    description: Allows managing player disabilities
    default: op

depend: [ProtocolLib]